[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
authors = [
   { name = "MY NAME", email = "my.email@address.com"},
]
name = "wbpj"
version = "0.0.1"
dependencies = [
    "numpy",
    "finufft"
]
